name: Publish
on:
  workflow_dispatch:
jobs:
  publish:
    name: Release build and publish
    runs-on: macOS-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Publish to MavenCentral
        run: |
          #./gradlew -Psign=true :core-data:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-domain:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-ui:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-permissions:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-location:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-time:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-auth:auth-data:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-auth:auth-domain:publishAndReleaseToMavenCentral --no-configuration-cache
          #./gradlew -Psign=true :core-auth:auth-ui:publishAndReleaseToMavenCentral --no-configuration-cache
          ./gradlew -Psign=true :core-auth:auth-api:publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}